name: Run Shell Script
on:
  push:
    branches: [ master ]  # 触发分支（可修改）
jobs:
  execute-script:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的虚拟机环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 拉取你的代码
      - name: Run Script
        run: |
          chmod +x update.sh  # 赋予执行权限（如果脚本没有权限）
          ./update.sh  # 执行你的脚本
