name: "refresh"

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # 以下步骤保留但优化了环境变量
      - name: Download remove_all_actions
        run: |
          sudo curl -L -o '/usr/bin/remove_all_actions' 'https://raw.githubusercontent.com/invalidunit/action/main/remove_all_actions'
          sudo chmod -R 0755 '/usr/bin/remove_all_actions'

      - name: Remove All Old Actions
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          remove_all_actions
